### ISSUE TITLE
licheePi hangs on booting

### ISSUE THREAD

**Issue by sadeghimoghaddam** [voloviq/meta-licheepizero#1]
hi , thanks for share this meta data
I build an Image with yocto and this layer
but in booting process licheePi hangs after this line of kernel log:
Starting Linux NFC daemon

and nothings happen!

**Comment by voloviq** [comment]
Hello,
Sometimes it is necessary to write an image for sdcard twice. I don't know why. Please check it.

**Comment by sadeghimoghaddam** [comment]
you mean that I must write to sd with dd comand twice ?????!!!
I will check it as soon as posible! but its intersting!! why! is there any difference between first "dd if=...." comand and second ?!

**Comment by sadeghimoghaddam** [comment]
I check again, with writing to sdcard twice! but nothing happen.
this is the last lines of my console log:


`
TNETLINK answers: File exists
[    5.710483] random: dbus-uuidgen: uninitialized urandom read (12 bytes read)
[    5.717785] random: dbus-uuidgen: uninitialized urandom read (8 bytes read)
Starting system message bus: dbus.
Starting random number generator daemon.
[   24.050807] random: crng init done
[   24.054235] random: 2 urandom warning(s) missed due to ratelimiting
Starting OpenBSD Secure Shell server: sshd
  generating ssh RSA host key...
  generating ssh ECDSA host key...
  generating ssh ED25519 host key...
done.
Starting rpcbind daemon...done.
Starting advanced power management daemon: No APM support in kernel
(failed.)
Starting bluetooth: bluetoothd.
Starting syslogd/klogd: done
[   28.074526] Bluetooth: Core ver 2.22
[   28.078226] NET: Registered protocol family 31
[   28.082843] Bluetooth: HCI device and connection manager initialized
[   28.089218] Bluetooth: HCI socket layer initialized
[   28.094129] Bluetooth: L2CAP socket layer initialized
[   28.099208] Bluetooth: SCO socket layer initialized
 * Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon
   ...done.
Starting Telephony daemon
Starting Linux NFC daemon

`

**Comment by voloviq** [comment]
Which branch did You use?

**Comment by voloviq** [comment]
I just started the latest yocot dunfell compilation (qt5-image). Feedback will be ready soon.

**Comment by sadeghimoghaddam** [comment]
I use seus branch like your README file:
git clone https://github.com/voloviq/meta-licheepizero --depth 1 -b zeus

I dont need qt at all!! I want just a metadata of LicheePi to build my own distro for it. but with this metaData LicheePizero-dock doesnt boot correctly ! and when we burn images of lichee website it boots corerctly!
thank you dear voloviq!

**Comment by voloviq** [comment]
Hang up confirmed. I check what is happening wrong.

**Comment by voloviq** [comment]
After investigation hang-up is not really hang up, just console redirection. Please change the line in licheepizero.conf or licheepizero-dock.conf

from
SERIAL_CONSOLE = "115200 ttyGS0"
to
SERIAL_CONSOLES = "115200;ttyS0"

Should works. "ttyGS0" is a virtual serial port "ttyS0" is a serial port on UART pins.

**Comment by sadeghimoghaddam** [comment]
> After investigation hang-up is not really hang up, just console redirection. Please change the line in licheepizero.conf or licheepizero-dock.conf
> 
> from
> SERIAL_CONSOLE = "115200 ttyGS0"
> to
> SERIAL_CONSOLES = "115200;ttyS0"
> 
> Should works. "ttyGS0" is a virtual serial port "ttyS0" is a serial port on UART pins.

Thanks!
it works
