### ISSUE TITLE
default password

### ISSUE THREAD

**Issue by sadeghimoghaddam** [voloviq/meta-licheepizero#2]
hello
I couldnt fild any default paswword for login!
How I can login to linux?? it needs password for root user!

I can define new user by :
inherit extrausers
EXTRA_USERS_PARAMS = "useradd -P 2015*08 myUser;"

but what is the default ? and in which file it is sets ?

**Comment by voloviq** [comment]
When I want to add a user I add the following lines in local.conf

```
# to enable a root password of myuser
INHERIT += "extrausers"
EXTRA_USERS_PARAMS = "usermod -P myuser root; "

# to force a password change on the first login
INHERIT += "chageusers"
CHAGE_USERS_PARAMS = "chage -d0 root; "
```

finally, You can disable root by commenting

```
# for an empty root password
# EXTRA_IMAGE_FEATURES = "debug-tweaks"
```

By default in my configuration, I just provide 'root' on login without any password.

Reference
https://docs.yoctoproject.org/singleindex.html
Chapter "6.33 extrausers.bbclass"
