### ISSUE TITLE
Implemented peripherals

### ISSUE THREAD

**Issue by AliMoal** [voloviq/meta-licheepizero#4]
Did this layer provide SPI, UART, PWM and other peripherals in lichee pi dock zero?

**Comment by voloviq** [comment]
Hi AliMoal,

everything depends on dts, but yes I checked UART, PWM and SPI. Everything work fine but peripherals are not customized on dts, You need to do this manually.

BR Michal

**Comment by AliMoal** [comment]
Thank you for your answer.
I have another problem. When I start to bitbake, this error will appear:
ERROR: u-boot-1_2020.01-r0 do_compile: oe_runmake failed.
I cleaned it by this command:
bitbake -c cleanall u-boot
and run bitbake again, but this error occur again.
What should I have to do?

**Comment by voloviq** [comment]
I try to reproduce the U-Boot compilation problem. Please write what OS You are using.

**Comment by AliMoal** [comment]
Ubuntu 22.04

**Comment by voloviq** [comment]
Please check the kirkstone branch. Should be compiled now.

**Comment by voloviq** [comment]
Can We close the issue?

**Comment by AliMoal** [comment]
Yes of course. If I had any other questions, I'd contact you.
