### ISSUE TITLE
usb host not work

### ISSUE THREAD

**Issue by mahdi2001h** [voloviq/meta-licheepizero#5]
I want to connect a usb keyboard to the licheepi zero , But after connecting it is not recognized

my branch is dunfell

**Comment by voloviq** [comment]
I updated dts. Please try 'kirkstone' branch. The reason of this is that oryginaly the Usb is configured as otg.

**Comment by voloviq** [comment]
Can You give some feedback whether it works? Thanks.

**Comment by mahdi2001h** [comment]
sorry.
I edited the files with the help of another source
Finally it worked properly

**Comment by mahdi2001h** [comment]
sorry.
I edited the files with the help of another source
Finally it worked properly
