### ISSUE TITLE
setup mipi camera interface for raspberry pi camera v2 ov5647 sensor

### ISSUE THREAD

**Issue by Mojtabanni** [voloviq/meta-licheepizero#7]
hello
I'm a big fan of you and your git repo. I'm using licheepi zero dock to capture image frames. I got image frame using DVP port and ov2640 sensor but I need LCD so I decide to use MIPI interface and  ov5647 sensor but I can't setup dts for MIPI-CSI2. I add drivers and peripherals needed by the MIPI-CSI2 but it doesn't recognize the sensor.

**Comment by voloviq** [comment]
Can You dump the boot log part related to ov5647?

**Comment by voloviq** [comment]
Unfortunately, this kind of sensor exists in different hardware configurations. I discovered that one type has just mipi plus enable pin but most have also i2c. Concerning this it is necessary to know which model You use, what is pin-to-pin hardware configuration is, and how looks now Your part of dts file with sensor settings. In my lab I have this device with i2c interface which is dedicated to RPI model 3B - 15pin with 1mm pitch. If You have the same model the hints You can find in dts of RPI 3B model.

**Comment by Mojtabanni** [comment]
thanks for your reply.
I am using raspberry pi camera v1.3 that has ov5647 sensor and 15 pins connector but also I have the   raspberry pi camera v2 with imx219 sensor. I will try the RPI model 3B dts and if I have the same error again I send the error here

**Comment by Mojtabanni** [comment]
I used rpi device tree but I got same error
here is the dmesg output
```
root@licheepizero-dock:~# dmesg | grep "csi"\n
[    1.260689] i2c 1-003c: Fixing up cyclic dependency with 1cb0000.csi\n
[    3.427634] sun6i-csi 1cb0000.csi: Unsupported media bus type\n
[    3.433452] sun6i-csi 1cb0000.csi: sun6i_csi_link_entity: no source pad in external entity (efault)\n
[    3.442618] sun6i-csi 1cb0000.csi: notifier registration failed\n
[    3.448916] sun6i-csi: probe of 1cb0000.csi failed with error -22\n
```
and also
```
root@licheepizero-dock:~# dmesg | grep "ov5647"
[    3.371545] ov5647 1-003c: write sensor_oe_enable_regs error
[    3.377281] ov5647: probe of 1-003c failed with error -110
```
I attach my dts file
[3.txt](https://github.com/voloviq/meta-licheepizero/files/13326520/3.txt)

**Comment by voloviq** [comment]
Hi Mojtabanni,

I try to help You a bit, but my experience with mipi cameras and cameras at all is not too big. Please confirm me if You are quite sure about the hardware connection correctness.

**Comment by voloviq** [comment]
Did You see
https://www.cnx-software.com/2023/11/17/allwinner-vpu-open-source-h264-hardware-video-encoder-linux-driver/

**Comment by Mojtabanni** [comment]
my hardware connection are correct. thanks for your reply. I will see this link and send send you the result.

**Comment by voloviq** [comment]
Is the problem with the camera resolved?

**Comment by Mojtabanni** [comment]
Yes. I solved my problem with this [https://github.com/aodzip/sun6i-mipi-csi](link) and add ov5647 to my kernel using `bitbake -c menuconfig virtual/kernel`
