### ISSUE TITLE
libstd-rs compile error with meta-toolchain-qt5

### ISSUE THREAD

**Issue by Mojtabanni** [voloviq/meta-licheepizero#8]
hello.
thanks for your repo again. when I try to `bitbake meta-toolchain-qt5` in kirkstone branch I have an error when it's going to compile `libstd-rs`.
I attach the log. in addition I change `yocto/poky/meta/recipes-devtools/rust/rust-common.inc` and add `arm-eabi` to it that attached too.
[log.do_compile.txt](https://github.com/voloviq/meta-licheepizero/files/13407509/log.do_compile.txt)
[rust-common.txt](https://github.com/voloviq/meta-licheepizero/files/13407533/rust-common.txt)

**Comment by voloviq** [comment]
Did You try
bitbake qt5-image -c populate_sdk
?

**Comment by Mojtabanni** [comment]
I tried it but it had some problem that I can't remember but I solved my problem for making SDK with using yout [https://github.com/voloviq/meta-cherrypi-v3s](meta-cherrypi) repo
